version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: securesight_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: grees@1234
      POSTGRES_DB: securesight_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: securesight_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
